package JAVA_Theory.Constructors;

public class C {
    //CONSTRUCTORS IS A SET OF INSTRUCTIONS USED FOR INITILIZATION[ASSIGNING] AND INSTANTIATION[OBJECT CREATION]
    //DEFAULT CONSTRUCTORS =>COMPILIER WILL AUTOMATICALLY GENERATE A CONSTRUCTOR CALLED DEFAULT CONSTRUCTOR
    public static void main(String[] args) {
        
    }
    
}
